#!/bin/bash

# Lightning Linux - Build Configuration Script
# Part of HarshitOS / Lightning Linux project
# https://github.com/jainh2095-sudo/Linux

set -e

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

# Function to print colored output
print_status() {
    echo -e "${BLUE}[INFO]${NC} $1"
}

print_success() {
    echo -e "${GREEN}[SUCCESS]${NC} $1"
}

print_warning() {
    echo -e "${YELLOW}[WARNING]${NC} $1"
}

print_error() {
    echo -e "${RED}[ERROR]${NC} $1"
}

# Default configuration
DEFAULT_CONFIG="
# Lightning Linux Build Configuration
# Generated by configure-build.sh

[General]
DISTRO_NAME="Lightning Linux"
DISTRO_VERSION="0.1"
DISTRO_CODENAME="Harshit"
ARCHITECTURE="$(uname -m)"
BUILD_DATE="$(date +%Y-%m-%d)"
BUILD_TIME="$(date +%H:%M:%S)"

[Kernel]
KERNEL_VERSION="6.1.85"
KERNEL_CONFIG="config/kernel/config-x86_64"
KERNEL_PATCHES="patches/kernel"
KERNEL_COMPRESSION="xz"

[Init]
INIT_SYSTEM="openrc"

[LibC]
LIBC_IMPLEMENTATION="glibc"

[Desktop]
DESKTOP_ENVIRONMENT="xfce4"
DISPLAY_MANAGER="lightdm"
WINDOW_MANAGER="picom"

[Optimizations]
ENABLE_ZRAM="yes"
ENABLE_ZSWAP="yes"
ENABLE_THP="yes"
IO_SCHEDULER="bfq"
CPU_GOVERNOR="schedutil"

[Packages]
INCLUDE_SECURITY="yes"
INCLUDE_DEVELOPMENT="yes"
INCLUDE_MEDIA="yes"
INCLUDE_OFFICE="yes"

[Output]
OUTPUT_DIR="build/output"
ISO_NAME="lightning-linux-\${DISTRO_VERSION}-\${ARCHITECTURE}.iso"
SQUASHFS_NAME="lightning-linux-\${DISTRO_VERSION}-\${ARCHITECTURE}.squashfs"
"

# Configuration file path
CONFIG_FILE="config/build.conf"

# Function to check if a command exists
command_exists() {
    command -v "$1" >/dev/null 2>&1
}

# Function to get user input with default
get_input() {
    local prompt="$1"
    local default="$2"
    local variable="$3"
    
    if [ -z "$default" ]; then
        read -p "$prompt: " $variable
    else
        read -p "$prompt [$default]: " $variable
        eval "$variable=\"${!$variable:-$default}\""
    fi
}

# Function to validate yes/no input
validate_yes_no() {
    local input="$1"
    case "$input" in
        [yY][eE][sS]|[yY])
            echo "yes"
            ;;
        [nN][oO]|[nN])
            echo "no"
            ;;
        *)
            echo "$input"
            ;;
    esac
}

# Function to display menu
show_menu() {
    clear
    echo ""
    echo "=========================================="
    echo "  Lightning Linux Build Configuration"
    echo "=========================================="
    echo ""
    echo "1.  Quick Configuration (Recommended)"
    echo "2.  Advanced Configuration"
    echo "3.  Load Existing Configuration"
    echo "4.  Save and Exit"
    echo "5.  Exit Without Saving"
    echo ""
    echo "Current Configuration File: $CONFIG_FILE"
    echo ""
}

# Function for quick configuration
quick_config() {
    print_status "Starting Quick Configuration..."
    
    # Get basic information
    get_input "Distribution Name" "Lightning Linux" DISTRO_NAME
    get_input "Distribution Version" "0.1" DISTRO_VERSION
    get_input "Distribution Codename" "Harshit" DISTRO_CODENAME
    
    # Architecture
    ARCHITECTURE=$(uname -m)
    print_status "Detected Architecture: $ARCHITECTURE"
    
    # Kernel
    get_input "Kernel Version" "6.1.85" KERNEL_VERSION
    
    # Init System
    echo ""
    print_status "Select Init System:"
    echo "1. OpenRC (Recommended for lightweight)"
    echo "2. systemd (Recommended for compatibility)"
    get_input "Init System (1-2)" "1" INIT_CHOICE
    case "$INIT_CHOICE" in
        1) INIT_SYSTEM="openrc" ;;
        2) INIT_SYSTEM="systemd" ;;
        *) INIT_SYSTEM="openrc" ;;
    esac
    
    # LibC
    echo ""
    print_status "Select LibC Implementation:"
    echo "1. glibc (Recommended for compatibility)"
    echo "2. musl (Recommended for lightweight)"
    get_input "LibC Implementation (1-2)" "1" LIBC_CHOICE
    case "$LIBC_CHOICE" in
        1) LIBC_IMPLEMENTATION="glibc" ;;
        2) LIBC_IMPLEMENTATION="musl" ;;
        *) LIBC_IMPLEMENTATION="glibc" ;;
    esac
    
    # Desktop Environment
    echo ""
    print_status "Select Desktop Environment:"
    echo "1. Xfce4 (Recommended for 2GB RAM)"
    echo "2. Openbox (Ultra-lightweight)"
    echo "3. LXQt (Lightweight Qt)"
    echo "4. None (Server/CLI only)"
    get_input "Desktop Environment (1-4)" "1" DE_CHOICE
    case "$DE_CHOICE" in
        1) DESKTOP_ENVIRONMENT="xfce4" ;;
        2) DESKTOP_ENVIRONMENT="openbox" ;;
        3) DESKTOP_ENVIRONMENT="lxqt" ;;
        4) DESKTOP_ENVIRONMENT="none" ;;
        *) DESKTOP_ENVIRONMENT="xfce4" ;;
    esac
    
    # Display Manager
    if [ "$DESKTOP_ENVIRONMENT" != "none" ]; then
        echo ""
        print_status "Select Display Manager:"
        echo "1. LightDM (Recommended)"
        echo "2. SDDM (Qt-based)"
        echo "3. None"
        get_input "Display Manager (1-3)" "1" DM_CHOICE
        case "$DM_CHOICE" in
            1) DISPLAY_MANAGER="lightdm" ;;
            2) DISPLAY_MANAGER="sddm" ;;
            3) DISPLAY_MANAGER="none" ;;
            *) DISPLAY_MANAGER="lightdm" ;;
        esac
    else
        DISPLAY_MANAGER="none"
    fi
    
    # Optimizations
    echo ""
    print_status "Enable Optimizations:"
    get_input "Enable ZRAM (yes/no)" "yes" ENABLE_ZRAM
    ENABLE_ZRAM=$(validate_yes_no "$ENABLE_ZRAM")
    
    get_input "Enable ZSWAP (yes/no)" "yes" ENABLE_ZSWAP
    ENABLE_ZSWAP=$(validate_yes_no "$ENABLE_ZSWAP")
    
    get_input "Enable THP (yes/no)" "yes" ENABLE_THP
    ENABLE_THP=$(validate_yes_no "$ENABLE_THP")
    
    # I/O Scheduler
    echo ""
    print_status "Select I/O Scheduler:"
    echo "1. BFQ (Recommended for HDDs)"
    echo "2. none (Recommended for SSDs/NVMe)"
    echo "3. kyber (Recommended for fast storage)"
    get_input "I/O Scheduler (1-3)" "1" IO_CHOICE
    case "$IO_CHOICE" in
        1) IO_SCHEDULER="bfq" ;;
        2) IO_SCHEDULER="none" ;;
        3) IO_SCHEDULER="kyber" ;;
        *) IO_SCHEDULER="bfq" ;;
    esac
    
    # CPU Governor
    echo ""
    print_status "Select CPU Governor:"
    echo "1. schedutil (Recommended for modern CPUs)"
    echo "2. ondemand (Recommended for older CPUs)"
    echo "3. performance (Maximum performance)"
    echo "4. powersave (Maximum power saving)"
    get_input "CPU Governor (1-4)" "1" CPU_CHOICE
    case "$CPU_CHOICE" in
        1) CPU_GOVERNOR="schedutil" ;;
        2) CPU_GOVERNOR="ondemand" ;;
        3) CPU_GOVERNOR="performance" ;;
        4) CPU_GOVERNOR="powersave" ;;
        *) CPU_GOVERNOR="schedutil" ;;
    esac
    
    # Package Groups
    echo ""
    print_status "Include Package Groups:"
    get_input "Include Security Tools (yes/no)" "yes" INCLUDE_SECURITY
    INCLUDE_SECURITY=$(validate_yes_no "$INCLUDE_SECURITY")
    
    get_input "Include Development Tools (yes/no)" "yes" INCLUDE_DEVELOPMENT
    INCLUDE_DEVELOPMENT=$(validate_yes_no "$INCLUDE_DEVELOPMENT")
    
    get_input "Include Media Applications (yes/no)" "yes" INCLUDE_MEDIA
    INCLUDE_MEDIA=$(validate_yes_no "$INCLUDE_MEDIA")
    
    get_input "Include Office Applications (yes/no)" "yes" INCLUDE_OFFICE
    INCLUDE_OFFICE=$(validate_yes_no "$INCLUDE_OFFICE")
    
    # Output
    get_input "Output Directory" "build/output" OUTPUT_DIR
    
    # Generate configuration
    generate_config
}

# Function for advanced configuration
advanced_config() {
    print_status "Advanced Configuration - Coming Soon!"
    print_warning "For now, using Quick Configuration..."
    quick_config
}

# Function to load existing configuration
load_config() {
    if [ -f "$CONFIG_FILE" ]; then
        print_status "Loading existing configuration from $CONFIG_FILE..."
        # For now, just display the file
        cat "$CONFIG_FILE"
        print_status ""
        print_status "Press Enter to continue..."
        read
    else
        print_warning "No existing configuration found at $CONFIG_FILE"
        print_status "Creating new configuration..."
        quick_config
    fi
}

# Function to generate configuration file
generate_config() {
    print_status "Generating configuration file..."
    
    # Create config directory if it doesn't exist
    mkdir -p config
    
    # Write configuration to file
    cat > "$CONFIG_FILE" <<EOF
# Lightning Linux Build Configuration
# Generated by configure-build.sh on $(date)

[General]
DISTRO_NAME="$DISTRO_NAME"
DISTRO_VERSION="$DISTRO_VERSION"
DISTRO_CODENAME="$DISTRO_CODENAME"
ARCHITECTURE="$ARCHITECTURE"
BUILD_DATE="$(date +%Y-%m-%d)"
BUILD_TIME="$(date +%H:%M:%S)"

[Kernel]
KERNEL_VERSION="$KERNEL_VERSION"
KERNEL_CONFIG="config/kernel/config-x86_64"
KERNEL_PATCHES="patches/kernel"
KERNEL_COMPRESSION="xz"

[Init]
INIT_SYSTEM="$INIT_SYSTEM"

[LibC]
LIBC_IMPLEMENTATION="$LIBC_IMPLEMENTATION"

[Desktop]
DESKTOP_ENVIRONMENT="$DESKTOP_ENVIRONMENT"
DISPLAY_MANAGER="$DISPLAY_MANAGER"
WINDOW_MANAGER="picom"

[Optimizations]
ENABLE_ZRAM="$ENABLE_ZRAM"
ENABLE_ZSWAP="$ENABLE_ZSWAP"
ENABLE_THP="$ENABLE_THP"
IO_SCHEDULER="$IO_SCHEDULER"
CPU_GOVERNOR="$CPU_GOVERNOR"

[Packages]
INCLUDE_SECURITY="$INCLUDE_SECURITY"
INCLUDE_DEVELOPMENT="$INCLUDE_DEVELOPMENT"
INCLUDE_MEDIA="$INCLUDE_MEDIA"
INCLUDE_OFFICE="$INCLUDE_OFFICE"

[Output]
OUTPUT_DIR="$OUTPUT_DIR"
ISO_NAME="lightning-linux-\${DISTRO_VERSION}-\${ARCHITECTURE}.iso"
SQUASHFS_NAME="lightning-linux-\${DISTRO_VERSION}-\${ARCHITECTURE}.squashfs"
EOF
    
    print_success "Configuration file generated at $CONFIG_FILE"
}

# Function to save and exit
save_and_exit() {
    if [ -f "$CONFIG_FILE" ]; then
        print_success "Configuration saved to $CONFIG_FILE"
        print_status ""
        print_status "=== Configuration Summary ==="
        print_status "Distribution: $DISTRO_NAME $DISTRO_VERSION ($DISTRO_CODENAME)"
        print_status "Architecture: $ARCHITECTURE"
        print_status "Kernel: $KERNEL_VERSION"
        print_status "Init System: $INIT_SYSTEM"
        print_status "LibC: $LIBC_IMPLEMENTATION"
        print_status "Desktop: $DESKTOP_ENVIRONMENT"
        print_status "Display Manager: $DISPLAY_MANAGER"
        print_status "Optimizations:"
        print_status "  - ZRAM: $ENABLE_ZRAM"
        print_status "  - ZSWAP: $ENABLE_ZSWAP"
        print_status "  - THP: $ENABLE_THP"
        print_status "  - I/O Scheduler: $IO_SCHEDULER"
        print_status "  - CPU Governor: $CPU_GOVERNOR"
        print_status "Packages:"
        print_status "  - Security: $INCLUDE_SECURITY"
        print_status "  - Development: $INCLUDE_DEVELOPMENT"
        print_status "  - Media: $INCLUDE_MEDIA"
        print_status "  - Office: $INCLUDE_OFFICE"
        print_status "Output Directory: $OUTPUT_DIR"
        print_status ""
        exit 0
    else
        print_error "No configuration to save!"
        exit 1
    fi
}

# Main script execution
print_status "Lightning Linux Build Configuration"
print_status "===================================="
print_status ""

# Check if config directory exists
if [ ! -d "config" ]; then
    mkdir -p config
fi

# Main loop
while true; do
    show_menu
    read -p "Select an option (1-5): " choice
    
    case $choice in
        1)
            quick_config
            save_and_exit
            ;;
        2)
            advanced_config
            save_and_exit
            ;;
        3)
            load_config
            ;;
        4)
            save_and_exit
            ;;
        5)
            print_status "Exiting without saving..."
            exit 0
            ;;
        *)
            print_error "Invalid option. Please try again."
            ;;
    esac
done

exit 0
